import "@mantine/core/styles.css";
import React from "react";
import { MantineProvider, ColorSchemeScript } from "@mantine/core";
import { theme } from "./lib/theme";
import NavBar from "./components/NavBar/NavBar";
import { NavbarSegmented } from "./components/NavBar/NavbarSegmented";

export const metadata = {
  title: "AI Novelist Library",
  description: "The stories generated by AI Novelist",
};

// RootLayout.tsx
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fa" dir="rtl">
      <head>
        <link rel="shortcut icon" href="/favicon.svg" />
        <link rel="preconnect" href="//fdn.fontcdn.ir" />
        <link rel="preconnect" href="//v1.fontapi.ir" />
        <link href="https://v1.fontapi.ir/css/Vazirmatn" rel="stylesheet" />
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
        />
        <meta
          name="format-detection"
          content="telephone=no, date=no, email=no, address=no"
        />
      </head>
      <body style={{ margin: 0, display: 'flex', height: '100vh' }}>
        <MantineProvider theme={theme}>
          <div style={{ display: 'flex', flex: 1, overflow: 'hidden' }}>
            {/* Navbar */}
            <NavbarSegmented />
            {/* Main Content */}
            <div style={{ flex: 1, overflow: 'auto' }}>
              {children}
            </div>
          </div>
        </MantineProvider>
      </body>
    </html>
  );
}

